spring.application.name=creditcardapplication

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_card_application
spring.datasource.username=postgres
spring.datasource.password=1234